### ISSUE TITLE
Why is this bad?

### ISSUE THREAD

**Issue by cored** [HouseTrip/guidelines#25]
https://github.com/HouseTrip/guidelines/blob/master/sustainable-testing.md#keep-models-thin-and-never-implement-business-logic-in-models

I'm wondering why don't you let the presentation logic inside the model for small things like this? Even if the SRP is broken because the model is doing two things persistence and presentation logic why sometimes the balance should point to removing the logic from it? Isn't this will make the code base hard to read and understand if you have a lot of smaller pieces to jump into?

**Comment by mezis** [comment]
Thanks for the comment @cored.

> I'm wondering why don't you let the presentation logic inside the model for small things like this

My point in writing this was that if you allow "small things", more will creep in, and you end up with a fat model all over again: it's a sustainability concern, particularly when dozens of engineers may act on the same codebase under pressure.

> Isn't this will make the code base hard to read and understand if you have a lot of smaller pieces to jump into?

Not necessarily.
If the model is thin, there's not much to understand about it at all (just relations, and non-contextual validations).
If the presentation / business logic is neatly organised into `presenters/` and `services/` directories, you'd probably find them easily?
Plus, `^[` in Vim would follow methods to their definitions?

**Comment by Davidslv** [comment]
:+1: @mezis I was working in a smaller project than HT and the model was full of presentation logic, it made it really hard to understand what was suppose to be part of the models (mostly nothing, as they were following `thin controllers` (not so thin either) and fat models).

@cored Separate your concerns, the guy after you will feel better when he doesn't have to jump into a 1000 lines model object that handles everything. A model should be responsible for validation and persistence and that's already quite a lot.

**Comment by cored** [comment]
@Davidslv I can see that from a conceptual point of view; my problem with this is that we are applying some logic into fields that are defined inside the model. The main advantage that I see from a testability point of view is that you can test the presentation in isolation without loading Rails; but where is the balance between that and understanding? /c @mezis

**Comment by pedrocunha** [comment]
Hello @cored, thanks for starting a discussion in an not-so agreed concept.

By the moment you add any behaviour to an object or add more interactions between objects you **always** increase complexity which then naturally also introduces an harder understanding of the whole system.

However complexity does not have to be the end of the world and there are a few tricks that an experienced developer will try to achieve:
- One class does only one thing and well
- Class and method names are well named, clear and obvious (single worded, easy to memorize, no get_* methods)
- Dependencies are none - or close to 0 (maybe 1-2 if generally you need some rails helpers)

Following the above rules, one would try to extract things very specifically to maybe only a small subset of pages of a whole web app. 

Let's say it's an admin page, and you need to display in a row specific user attributes, you probably will want to create some sort of `Admin::UserPresenter` that has a method #attributes, your admin controller would probably instantiate it and your view(s) use it.

The beauty now is that anything related to Admin, is now inside app/presenters/admin, app/controllers/admin etc.. you get the point, and probably someone with any decent file autocomplete will probably type "adminuser" and spots right away where things are. 

This will also enable other more interesting things: for example while testing you don't really need to work with real activerecord objects. Maybe just a mock model or `instance_double`(s) from RSpec will suffice and allows you to test and progress faster.

In the real world I've seen situations also that you would never do "#full_name" methods in ActiveModels but do this:

```ruby
# app/helpers/user_helper.rb
def full_name(user)
  UserPresenter.new(user).full_name
end
```

This can also be an interesting pattern if you don't want to mess around with loads of crazy objects in your controllers and over-extending classes / adding concerns.

The bottomline is: do what you feel is better for you and your team, and always keep an open spirit for new ideas that show up. In the end, what you want to achieve is, no matter if you have a 5000 LOC project, you still want to be able to:
- Run the test suite fast enough to get feedback
- Navigate easily through even though no-one will probably ever have 100% knowledge of the whole codebase

My 0.02 :money_with_wings:

**Comment by cored** [comment]
Totally agree with this. The thing is that at some point it was kinda hard
for me to create this balance on not having too many objects. But you are
right using vim you can solve this issue very easily and in the end what we
are looking for is just to have systems that are easy to change in the
future.
